# Generated by Django 2.1.15 on 2020-06-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField()),
                ('movie_id', models.IntegerField()),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('poster_path', models.TextField()),
                ('production_companies', models.TextField()),
                ('production_countries', models.TextField()),
                ('release_date', models.CharField(max_length=30)),
                ('revenue', models.IntegerField()),
                ('runtime', models.IntegerField()),
                ('spoken_language', models.CharField(max_length=30)),
                ('tagline', models.TextField()),
                ('title', models.TextField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
            ],
        ),
    ]
