# Generated by Django 2.2.6 on 2020-06-12 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='production_company',
            field=models.ManyToManyField(related_name='movies', to='movies.Production_company'),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_country',
            field=models.ManyToManyField(related_name='movies', to='movies.Production_country'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='revenue',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='runtime',
            field=models.FloatField(),
        ),
    ]
